version: '3.8'
services:
  mc:
    # https://github.com/itzg/docker-minecraft-bedrock-server
    image: itzg/minecraft-bedrock-server
    environment:
      - EULA=TRUE
    ports:
      - 19132:19132/udp
    volumes:
      - ./mc-bedrock-data:/data
    restart: always
  dns:
    image: jpillora/dnsmasq
    restart: always
    environment:
      - HTTP_USER=foo
      - HTTP_PASS=bar
    ports:
      - 53:53/udp
      # web ui
      - 5380:5380
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./etc-hosts:/etc/hosts
    # --log-opt "max-size=100m"
